### ISSUE TITLE
pops up an error when clicking 'Reinforce policies'

### ISSUE THREAD

**Issue by czz404** [hellzerg/optimizer#400]
**Describe the bug**
The program pops up an error when clicking 'Reinforce policies'
message ：
[message.txt](https://github.com/hellzerg/optimizer/files/12906620/message.txt)

**Screenshots**
![pic_1697297461.png](https://s2.loli.net/2023/10/14/tf6D9wUOI12rK3E.png)

**Logs**
[Optimizer.log](https://github.com/hellzerg/optimizer/files/12906607/Optimizer.log)

**Desktop (please complete the following information):**
 - Windows version and build ：Win11 22H2 22621.2428
- .NET Frameworks installed ：Microsoft .NET Runtime -6.0.23 （x64、x86)
 - Optimizer version ：15.9

**Comment by hellzerg** [comment]
Just fixed with v16.0!

**Comment by czz404** [comment]
Sorry, I still have the same problem in version 16
message：
[message.txt](https://github.com/hellzerg/optimizer/files/12908223/message.txt)
Logs
[Optimizer.log](https://github.com/hellzerg/optimizer/files/12908224/Optimizer.log)
